name: Build

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
      - "**/*.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.go"
      - "**/*.mod"
      - "**/*.sum"
      - "**/*.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        goos: [windows, freebsd, openbsd, linux, dragonfly, darwin]
        goarch: [amd64, 386]
        exclude:
          - goarch: 386
            goos: darwin
          - goarch: 386
            goos: dragonfly
        include:
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: arm64
          - goos: linux
            goarch: riscv64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: loong64
          - goos: linux
            goarch: mips64
          - goos: linux 
            goarch: mips64le
          - goos: linux
            goarch: mips
          - goos: linux
            goarch: mipsle
            gomips: softfloat # mt7621
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOMIPS: ${{ matrix.gomips}}
      GO111MODULE: on
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
          check-latest: true
      - name: Build
        run: go build -ldflags="-s -w" -o bin/${{ matrix.goos }}_${{ matrix.goarch }}/main


      - name: Run UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          files: bin/${{ matrix.goos }}_${{ matrix.goarch }}/main
          args: -fq || 0  # 报错不退出

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.goos }}_${{ matrix.goarch }}
          path: bin/${{ matrix.goos }}_${{ matrix.goarch }}/main
          retention-days: 1

